--------------------------------------------------------------------------
--script for auto_funcs.h and auto_funcs.cpp generation
--expects LuaJIT
--------------------------------------------------------------------------

--load parser module
package.path = package.path..";../../cimgui/generator/?.lua"
local cpp2ffi = require"cpp2ffi"
local save_data = cpp2ffi.save_data
local copyfile = cpp2ffi.copyfile
--take script args---------------------------
local COMPILER, CPRE, INTERNAL_GENERATION, COMMENTS_GENERATION = cpp2ffi.GetScriptArgs({},...)
--------------------------------------------------------------------------
--this table has the functions to be skipped in generation
--------------------------------------------------------------------------
local cimgui_manuals = {
    -- igLogText = true,
    -- ImGuiTextBuffer_appendf = true,
}
--------------------------------------------------------------------------
--this table is a dictionary to force a naming of function overloading (instead of algorythmic generated)
--first level is cimguiname without postfix, second level is the signature of the function, value is the
--desired name
---------------------------------------------------------------------------
local cimgui_overloads = {
    --igPushID = {
        --["(const char*)"] =           "igPushIDStr",
        --["(const char*,const char*)"] = "igPushIDRange",
        --["(const void*)"] =           "igPushIDPtr",
        --["(int)"] =                   "igPushIDInt"
    --},
}

--------------------------header definitions
local cimgui_header = 
[[//This file is automatically generated by generator.lua from https://github.com/cimgui/cimguizmo
//based on ImGuizmo.h file version XXX from https://github.com/CedricGuillemet/ImGuizmo
]]
--------------------------------------------------------------------------
--helper functions
--------------------------------functions for C generation



--------------------------------------------------------
-----------------------------do it----------------------
--------------------------------------------------------
--get implot.h version--------------------------
local pipe,err = io.open("../ImGuizmo/ImGuizmo.h","r")
if not pipe then
    error("could not open file:"..err)
end
local implot_version
while true do
    local line = pipe:read"*l"
    implot_version = line:match([[%s+v(.+)]])
    if implot_version then break end
end
pipe:close()
cimgui_header = cimgui_header:gsub("XXX",implot_version)
print("IMGUIZMO_VERSION",implot_version)


-------------funtion for parsing implot headers
local function parseImGuiHeader(header,names,modulename)
	--prepare parser
	local parser = cpp2ffi.Parser()
	parser.modulename = modulename
	parser.getCname = function(stname,funcname,namespace)
		local pre = (stname == "") and (namespace and (namespace=="ImGui" and "ig" or namespace.."_") or "ig") or stname.."_"
		return pre..funcname
	end
	parser.cname_overloads = cimgui_overloads
	parser:set_manuals(cimgui_manuals, modulename)
	--parser.UDTs = {"ImVec2","ImVec4","ImColor","ImRect"}--,"ImPlotPoint","ImPlotLimits"}
	parser.cimgui_inherited =  dofile([[../../cimgui/generator/output/structs_and_enums.lua]])
	--ParseItems cleaning of c++ attributes
	parser.str_subst = {["%[%[[^%[%]]+%]%]"] = ""}
	parser.COMMENTS_GENERATION = COMMENTS_GENERATION
	local include_cmd = COMPILER=="cl" and [[ /I ]] or [[ -I ]]
	local extra_includes = include_cmd.." ../../cimgui/imgui "

	parser:take_lines(CPRE..extra_includes..header, names, COMPILER)
	
	return parser
end
--generation
print("------------------generation with "..COMPILER.."------------------------")
local modulename = "cimguizmo"

local headerst = [[#include "../ImGuizmo/ImGuizmo.h"
]]
--headerst = headerst .. [[#include "../ImGuizmo/GraphEditor.h"
--]]
save_data("headers.h",headerst)
local parser1 = parseImGuiHeader([[headers.h]],{[[ImGuizmo]],[[GraphEditor]]},modulename)
os.remove("headers.h")

parser1:do_parse()

-- save_data("./output/overloads.txt",parser1.overloadstxt)
--cimgui_generation(parser1,modulename)
parser1:cimgui_generation(cimgui_header)
parser1:save_output()

print"all done!!"
